### ISSUE TITLE
GBL gets detected as CN

### ISSUE THREAD

**Issue by shimizu-izumi** [Kxnrl/StarRailRpc#2]
For some reason the global version is detected as the Chinese version

**Comment by Kxnrl** [comment]
![image](https://user-images.githubusercontent.com/3905845/235966717-0a492bb9-92b4-4349-96bb-dc8ac0b7e77a.png)
Fixed in https://github.com/Kxnrl/StarRailRpc/commit/5cfb6e50ae4bdddcef614bd24d8984ad619c38f2
