### ISSUE TITLE
GBL Star Rail not detected

### ISSUE THREAD

**Issue by shimizu-izumi** [Kxnrl/StarRailRpc#3]
After the changes in 5cfb6e50ae4bdddcef614bd24d8984ad619c38f2 the global version doesn't get detected for me.

OS: Windows 11 Pro
OS Version: 22H2
OS Build: 22621.1635

**Comment by shimizu-izumi** [comment]
I cloned the source and the global version can't be found with "崩坏：星穹铁道" as the window name

**Comment by Kxnrl** [comment]
can you show the screenshot?
I think mihoyo use i18n for window title.

**Comment by shimizu-izumi** [comment]
I think I was able to fix it. I will test it for the CN version and make a pull request if it works

**Comment by shimizu-izumi** [comment]
Well, I can't test it for the CN version because the launcher won't let me download it, and gives me the message "Searching for updates"

**Comment by NyanCat4709** [comment]
How did you fix it for global? I’m having the same issue, it doesn’t work :( Only the previous version did but it displays it in CN

**Comment by shimizu-izumi** [comment]
You can wait for the dev to merge the open pull request, then it will work.
